generator:
  class: sfDoctrineGenerator
  param:
    model_class:           pkBlogPost
    theme:                 pkAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pk_blog_post_admin
    with_doctrine_route:     1

    config:
      actions: 
        _new:
          label: Create New Post
      fields:
        author_id:
          help: Specify the author of your post. Admins are permitted to specify the author of a post. Editors are only permitted to publish as themselves.
        title:
          help: Specify the title of your post.
        body:
          help: Use the rich text editor to format the body of your post.
        excerpt:
          help: Specify an excerpt from the body of your post. The excerpt will be displayed in the paginated blog archive and wherever a blog post slot is added.
        category_id:
          help: 'Specify a category for your post. Categories are hierarchical, you may only specify one.'
        tags:
          help: 'Add any relevant tags to your post, separated by commas. Select recommended tags to prevent creating duplicates.'
        published:
          help: Specify whether your post should go live or remain a draft.
        published_at:
          help: 'Specify a published date. You can back-date posts, or set them to be published in the future.'
      list:
        title: Blog Posts
        display: [_post, author, category, _media]
        object_actions:
          _edit:      ~
          media:
            label:  Manage media
            action: media
            params: class=pk-btn icon icon-only pk-media
          _delete:    ~
        batch_actions:
          _delete:    ~
          publish:
            label:    Publish/Unpublish
      filter:  ~
      form:
        display: [author_id, title, body, excerpt, category_id, published, published_at, tags, ~tagList]
      edit:
        title: Editing Post - "%%title%%"
        actions:
          _save:      ~
          publish:
            label:    Publish/Unpublish
            action:   publish
            params:   class=pk-btn icon pk-publish
          _list:      ~
          _delete:    ~
      new:
        title: New Post
        actions:
          _save:      ~
          _list:      ~
          _delete:    ~
