<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginpkBlogEvent extends BasepkBlogEvent
{
  public function getPermalink()
  {
    sfContext::getInstance()->getConfiguration()->loadHelpers('Url');
    
    return url_for('pk_calendar_post', $this, false);
  }
  
  public function getStartDateTime()
  {
    return strtotime($this->getStartDate() .' '. $this->getStartTime());
  }
}