<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginpkBlogPostTable extends Doctrine_Table
{
  public function buildQuery(sfWebRequest $request)
  {
    if ($request->getParameter('tag'))
    {
      $q = PluginTagTable::getObjectTaggedWithQuery('pkBlogPost', $request->getParameter('tag'), null, array('nb_common_tag' => 1));
    }
    else
    {
      $q = Doctrine_Query::create()->from('pkBlogPost a');
    }
    
    if ($request->getParameter('search'))
    {
      $q = Doctrine::getTable('pkBlogPost')->addSearchQuery($q, $request->getParameter('search'));
    }
    
    $rootAlias = $q->getRootAlias();
    
    // if it's an RSS feed, we don't want to be concerned with a time frame, just give us the latest stuff
    if ($request->getParameter('format') != 'rss')
    {
      $q->addWhere($rootAlias.'.published_at > ?', $request->getParameter('year', date('Y')).'-'.$request->getParameter('month', 1).'-'.$request->getParameter('day', 1).' 0:00:00')
        ->addWhere($rootAlias.'.published_at < ?', $request->getParameter('year', date('Y')).'-'.$request->getParameter('month', 12).'-'.$request->getParameter('day', 31).' 23:59:59');
    }
    
    if ($request->getParameter('cat'))
    {
      $q->innerJoin($rootAlias.'.Category c WITH c.slug = ? ', $request->getParameter('cat'));
    }
    
    $q->addWhere($q->getRootAlias().'.published = ?', true);

    $q->orderBy($rootAlias.'.published_at desc');
    
    return $q;
  }
  
  public function getLuceneIndex()
  {
    return pkZendSearch::getLuceneIndex($this);
  }
   
  public function getLuceneIndexFile()
  {
    return pkZendSearch::getLuceneIndexFile($this);
  }

  public function searchLucene($luceneQuery)
  {
    return pkZendSearch::searchLucene($this, $luceneQuery);
  }

  public function searchLuceneWithScores($luceneQuery)
  {
    return pkZendSearch::searchLuceneWithScores($this, $luceneQuery);
  }
  
  public function rebuildLuceneIndex()
  {
    return pkZendSearch::rebuildLuceneIndex($this);
  }
  
  public function optimizeLuceneIndex()
  {
    return pkZendSearch::optimizeLuceneIndex($this);
  }
  
  public function addSearchQuery(Doctrine_Query $q = null, $luceneQuery)
  {
    return pkZendSearch::addSearchQuery($this, $q, $luceneQuery, null);
  }

  public function addSearchQueryWithScores(Doctrine_Query $q = null, $luceneQuery, &$scores)
  {
    return pkZendSearch::addSearchQueryWithScores($this, $q, $luceneQuery, null, $scores);
  }
}