<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginpkContextCMSBlogPostSlot extends BasepkContextCMSBlogPostSlot
{
  protected $editDefault = true;
}